insert into colegios (nombre) values ("NST DE BTO TEC COMERCIAL PITAGORAS ")                                                                
insert into colegios (nombre) values ("GIMNASIO INFANTIL FEDERICO FROEBEL")
insert into colegios (nombre) values ("GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA")
insert into colegios (nombre) values ("COLEGIO FRANCISCO PRIMERO S.S. (IED)")
insert into colegios (nombre) values ("COL SAN JUAN VIANETH ")                                                                               
insert into colegios (nombre) values ("COL SAN PATRICIO ")                                                                                   
insert into colegios (nombre) values ("COL CRISTIANO FUENTE DE VIDA ")                                                                       
insert into colegios (nombre) values ("LIC PARROQ SAN JOSE ")                                                                                
insert into colegios (nombre) values ("LIC ESTRELLITA ESTUDIANTIL ")                                                                         
insert into colegios (nombre) values ("COL LUIGI PIRANDELLO")
insert into colegios (nombre) values ("JARDIN INFANTIL CAMPESTRE MI BELLA IMAGEN ")                                                          
insert into colegios (nombre) values ("COLEGIO MARCO FIDEL SUAREZ (IED)")
insert into colegios (nombre) values ("INST ORESTES SINDICI ")                                                                               
insert into colegios (nombre) values ("COL DEL BOSQUE ")                                                                                     
insert into colegios (nombre) values ("INST SANTA INES ")                                                                                    
insert into colegios (nombre) values ("CENTRO DE EDUCACION LABORAL")
insert into colegios (nombre) values ("LIC ADOLFO LEON GOMEZ ")                                                                              
insert into colegios (nombre) values ("COL CENTRO CULTURAL ")                                                                                
insert into colegios (nombre) values ("LIC PEDAGOGICO  LOS SAUCES ")                                                                         
insert into colegios (nombre) values ("LIC SANTA PAULA")
insert into colegios (nombre) values ("COL DEL SAGRADO CORAZON DE JESUS BETHLEMITAS ")                                                       
insert into colegios (nombre) values ("COL ADOLFO LEON GOMEZ")
insert into colegios (nombre) values ("GIMNASIO NUESTRA SEÑORA DE LA ESPERANZA")
insert into colegios (nombre) values ("COL INTEGRADO SANTO TORIBIO DE MOGROVEJO ")                                                           
insert into colegios (nombre) values ("GIMN WILLIAM MACKINLEY ")                                                                             
insert into colegios (nombre) values ("LICEO BET-EL")
insert into colegios (nombre) values ("COLEGIO INTEGRADO EDUARDO CABALLERO CALDERON")
insert into colegios (nombre) values ("COLEGIO GUSTAVO MORALES MORALES (IED)")
insert into colegios (nombre) values ("LIC PSICOPEDAG UCRANIA ")                                                                             
insert into colegios (nombre) values ("LIC PSICOPEDAG MORATO ")                                                                              
insert into colegios (nombre) values ("LICEO ARTISTICO SAN JOSE")
insert into colegios (nombre) values ("COLEGIO INSTITUTO TECNICO DISTRITAL REPUBLICA DE GUATEMALA (IED)")
insert into colegios (nombre) values ("INST ANDRES FEY ")                                                                                    
insert into colegios (nombre) values ("INST DE CAPACITACION PARA EL TRABAJO")
insert into colegios (nombre) values ("NUEVO LIC SANTA CLARA")
insert into colegios (nombre) values ("LIC MODERNO MIS COMPAÑERITOS ")                                                                       
insert into colegios (nombre) values ("JARD INF LERNER Y KLEIN ")                                                                            
insert into colegios (nombre) values ("INSTITUTO DANTE ALIGHIERI")
insert into colegios (nombre) values ("COLEGIO ALEJANDRO OBREGON (IED)")
insert into colegios (nombre) values ("LIC  ANDRES DIAZ VENERO DE LEIVA ")                                                                   
insert into colegios (nombre) values ("JARD INF TALLER EL GARABATEO MATERNO INFANTIL")
insert into colegios (nombre) values ("JARDIN INFANTIL UNIVERSO MAGICO")
insert into colegios (nombre) values ("COLEGIO ANTONIO JOSE URIBE (IED)")
insert into colegios (nombre) values ("COL DE LA PRESENTACION SANS FACON ")                                                                  
insert into colegios (nombre) values ("LIC EL ENCUENTRO ")                                                                                   
insert into colegios (nombre) values ("INST MARIA ")                                                                                         
insert into colegios (nombre) values ("COLEGIO AGUSTIN FERNANDEZ (IED)")
insert into colegios (nombre) values ("EL PORTAL FUNDACION ")    
insert into colegios (nombre) values ("COLEGIO CEDID SAN PABLO (IED)")
insert into colegios (nombre) values ("COL NUEVA INGLATERRA ")                                                                               
insert into colegios (nombre) values ("GIMN IMPERIAL IGNACIA CAMACHO DE CIFUENTES ")                                                         
insert into colegios (nombre) values ("COLEGIO LA PAZ (CED)")
insert into colegios (nombre) values ("NUEVO COL BILING LARCHMONT")
insert into colegios (nombre) values ("LIC PSICOPEDAG SAN PABLO")
insert into colegios (nombre) values ("COLEGIO KUEPA")
insert into colegios (nombre) values ("JARD INF PITIN ")                                                                                     
insert into colegios (nombre) values ("CENT FE Y ALEGRIA PATIO BONITO ")                                                                     
insert into colegios (nombre) values ("JARD INF SATELITE PRIMAVERA")
insert into colegios (nombre) values ("COLEGIO ALEXANDER FLEMING (IED)")
insert into colegios (nombre) values ("JARDÍN INFANTIL CHISPITAS DE LUZ")
insert into colegios (nombre) values ("COL MODERNO ENGATIVA ")                                                                               
insert into colegios (nombre) values ("COL SANTO TOMAS DE AQUINO ")                                                                          
insert into colegios (nombre) values ("GIMNASIO LA FONTAINE")
insert into colegios (nombre) values ("UNID PREESC SANTA MONICA ")                                                                           
insert into colegios (nombre) values ("COL DE BTO PATRIA ")                                                                                  
insert into colegios (nombre) values ("LICEO HUELLAS DE TRIUNFO")
insert into colegios (nombre) values ("LIC DE CERVANTES EL RETIRO ")                                                                         
insert into colegios (nombre) values ("COLEGIO ALEMANIA UNIFICADA (IED)")
insert into colegios (nombre) values ("NUEVO LIC PSICOPEDAGOGICO ")                                                                          
insert into colegios (nombre) values ("INST RICHARD ANTONIO ")                                                                               
insert into colegios (nombre) values ("LIC INF MIS PRIMEROS LOGROS ")                                                                        
insert into colegios (nombre) values ("LIC OCTAVIO PAZ ")                                                                                    
insert into colegios (nombre) values ("COLEGIO JOSÉ FRANCISCO SOCARRÁS (IED)")
insert into colegios (nombre) values ("COLEGIO NUEVA GENERACIÓN DUMBO")
insert into colegios (nombre) values ("INST BILING DEL  SUR ")                                                                               
insert into colegios (nombre) values ("COLEGIO VENTIUN ANGELES (IED)")
insert into colegios (nombre) values ("GIMN PUCIARRELLI")
insert into colegios (nombre) values ("COLEGIO FRANCISCO DE PAULA SANTANDER (IED)")
insert into colegios (nombre) values ("COL DEL ROSARIO DE SANTO DOMINGO ")                                                                   
